version: '3.4'

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile
    command: bash -c "./manage.py collectstatic --no-input && ./manage.py migrate --no-input && gunicorn -c gunicorn.conf.py config.wsgi"
    volumes:
      - .:/app
      - ./media:/app/media
    ports:
      - 8000:80
    env_file:
      - ./.env
    depends_on:
      - db

  db:
    image: postgres
    volumes:
      - "postgres_data:/var/lib/postgresql/data/"
    env_file:
      - ./.env

volumes:
  postgres_data:
  media:
